#!/usr/bin/env python3
"""Translate leftover English fragments in dictionary + kanji JSON."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path("/workspace")
DICT = ROOT / "src/data/dictionary-jlpt.json"
KANJI = ROOT / "src/data/kanji-jlpt.json"

# Phrase / whole-gloss first (lowercased keys).
PHRASE = {
    "oneself": "bản thân",
    "brush-stroke": "nét vẽ",
    "katakana e radical (no. 48)": "bộ công",
    "three-stroke": "ba nét",
    "counter suits quần áo": "loại từ đếm bộ quần áo",
    "western phong cách": "phong cách Tây",
    "boiled gạo": "cơm",
    "gạo paddy": "ruộng lúa",
    "pine tree": "cây thông",
    "best-seller": "sách bán chạy",
    "x-quang": "x-quang",
    "pitch accent": "cao độ",
    "long-distance": "đường dài",
    "one-sided": "một phía",
    "warship": "tàu chiến",
    "eyeball": "nhãn cầu",
    "tombstone": "bia mộ",
    "chrysanthemum": "cúc",
    "lightning-bug": "đom đóm",
    "bowstring": "dây cung",
    "silkworm": "tằm",
    "freshwater trout": "cá hồi nước ngọt",
    "imperial edict": "chiếu chỉ",
    "imperial order": "sắc lệnh",
    "ground-breaking": "khai phá",
    "lapis lazuli": "ngọc lưu ly",
    "mandarin orange": "quýt",
    "deciduous tree": "cây lá rụng",
    "reed instrument": "sáo sậy",
    "butterbur": "cây ngưu bàng Nhật",
    "blackened eyebrows": "lông mày vẽ",
    "comma-design": "họa tiết tomoe",
    "serving our elders": "hiếu kính người trên",
    "male mythical bird": "phượng",
    "japanese judas-tree": "cây quế",
    "two-mat area": "diện tích hai chiếu",
    "ten-day thời kỳ": "mười ngày",
    "animal sacrifice": "tế vật",
    "meritorious deed": "công trạng",
    "bush clover": "cây hagi",
    "self-effacing": "khiêm nhường",
    "direct descent (non-bastard)": "con đích",
    "keep rain)out": "che mưa",
    "the pleiades": "sao Tua Rua",
    "ancestral offering receptacle": "đồ cúng tổ",
    "coarse camlet": "vải thô",
    "consult with": "bàn bạc",
    "audience (with king)": "yết kiến",
    "majestic plural": "trẫm",
    "brilliant fabric design": "hoa văn rực rỡ",
    "conjunction (astronomy)": "hợp nhật",
    "first ngày tháng": "mồng một",
    "show symptoms of": "manh nha",
    "one (in documents)": "một (văn thư)",
    "dấu hiệu ox cow": "sửu",
    "dấu hiệu hog": "hợi",
    "dấu hiệu rat": "tý",
    "11pm-1am": "23–1 giờ",
    "1-3am": "1–3 giờ",
    "9-11pm": "21–23 giờ",
    "going": "đi",
    "to be (classical)": "là (cổ văn)",
    "counter for articles": "loại từ đếm món",
    "counter loaves bánh mì": "loại từ đếm ổ bánh",
    "8 liter": "8 lít",
    "75 grams": "75 gam",
    "32 lb": "ước 14,5 kg",
    "1 · 10 sen": "1/10 sen",
    "8 1 · 3lbs": "khoảng 3,75 kg",
    "245 acres": "khoảng 1 km²",
    "counter nights ở lại": "loại từ đếm đêm nghỉ",
    "counter phẳng objects": "loại từ đếm tấm",
    "government ministry": "bộ (chính phủ)",
    "buddhist temple": "chùa",
    "buddhist priest": "nhà sư",
    "buddhist surplice": "áo cà sa",
    "manchu dynasty": "nhà Tần",
    "hanging scroll": "tranh cuộn",
    "fortune-telling": "bói toán",
    "social lớp": "tầng lớp",
    "bottom giá": "đáy",
    "go-between": "người môi giới",
    "giấy tiền": "tiền giấy",
    "yếu trà": "nhạt",
    "60 phút": "phút",
    "writing bút lông": "bút lông",
    "put trên at": "đậu (tàu)",
    "cưỡi at anchor": "thả neo",
    "chịu burden": "gánh",
    "shoulder (a gun)": "vác",
    "nóng nước": "nước nóng",
    "nóng mùa xuân": "suối nước nóng",
    "đầu pimple": "mụn",
    "passage thời gian": "thời gian trôi",
    "cửa radical no 63": "bộ hộ",
    "sông radical no 47": "bộ xuyên",
    "quyền làng radical no 163": "bộ ấp",
    "wide(ly": "rộng",
    "laid waste": "hoang tàn",
    "be filled trên": "lấp đầy",
    "dâng prayers": "cầu nguyện",
    "put trên with": "chịu đựng",
    "cut out pattern": "cắt mẫu",
    "put trên tent": "dựng lều",
    "counter for bows": "loại từ đếm cung",
    "stringed instruments": "nhạc cụ dây",
    "opposition (astronomy)": "xung đối",
    "signature (of artisan)": "minh (thợ)",
    "lấy warning from": "răn mình",
    "học from": "học theo",
    "rising mặt trời": "bình minh",
    "buổi sáng mặt trời": "mặt trời mọc",
    "leaping trên": "vọt lên",
    "jumping trên": "nhảy lên",
    "chi nhánh off": "rẽ nhánh",
    "fork đường": "ngã ba",
    "dùng trên": "dùng hết",
    "chạy out": "cạn",
    "phường off": "chống lại",
    "làm noise": "làm ồn",
    "đau buồn over": "thương tiếc",
    "xấu looking": "xấu xí",
    "above-stated": "nêu trên",
    "send forth fragrance": "tỏa hương",
    "miscanthus reed": "cỏ lau",
    "cultural progress": "văn minh",
    "charging ahead of others": "đi đầu",
    "venerable old man": "ông lão",
    "type of deciduous tree": "cây lá rụng",
    "a reed instrument": "sáo sậy",
    "chinese parasol cây": "ngô đồng",
    "phoenix cây": "cây ngô đồng",
    "affix con dấu": "đóng dấu",
    "samisen nhạc": "nhạc shamisen",
    "third lớp": "hạng ba",
    "sâu broad nước": "nước rộng sâu",
    "how nhiều": "bao nhiêu",
    "how dài": "bao lâu",
    "even số": "số chẵn",
    "nam & vợ": "vợ chồng",
    "once upon thời gian": "ngày xưa",
    "có danh dự to": "kính thưa",
    "dấu hiệu monkey": "thân (con giáp)",
    "counter lớn animals": "loại từ đếm thú lớn",
    "đi along": "đi dọc",
    "đi bộ along": "đi bộ dọc",
    "lấy along": "mang theo",
    "chạy along": "chạy dọc",
    "đi beyond": "vượt",
    "điểm out": "chỉ ra",
    "điểm to": "chỉ",
    "coming & đi": "đi lại",
    "be at hòa bình": "yên",
    "bình tĩnh dưới": "bình tĩnh",
    "lấy trên": "đảm nhận",
    "lớn lên trên": "nuôi dưỡng",
    "bring trên": "nuôi",
    "thức trên": "thức dậy",
    "được trên": "được",
    "đứng trên": "đứng",
    "set trên": "đặt",
    "rõ trên": "quang đãng",
    "cheer trên": "cổ vũ",
    "uống trên": "uống cạn",
    "lớp first": "hạng nhất",
    "cũ nam": "ông già",
    "cũ tuổi": "tuổi già",
    "rõ out": "quét sạch",
    "cắt off": "cắt đứt",
    "cắt tốt": "khắc",
    "lớn around": "to béo",
    "climb trên": "trèo",
    "division (x · 3": "chia",
    "counter for carriages (e.g.": "loại từ đếm xe",
    "feelings": "cảm xúc",
    "invariably": "nhất định",
    "three (in documents)": "ba (văn thư)",
    "người charge": "phụ trách",
    "một charge": "phụ trách",
    "main vật": "chủ",
    "main điểm": "điểm chính",
    "odd số": "số lẻ",
    "ngày off": "ngày nghỉ",
    "đi out": "đi ra",
    "đi off nhiệm vụ": "tan ca",
    "shed nước mắt": "rơi lệ",
    "đến at": "đến",
    "dẫn to": "dẫn tới",
    "nghĩ over": "suy nghĩ",
    "former thời gian": "trước kia",
    "thủ đô · 10**16": "kinh đô",
    "đúng · 10**40": "đúng",
    "10**12": "nghìn tỷ",
    "trăm million · 10**8": "ức",
    "full tháng": "rằm",
    "đầy tháng": "rằm",
    "-ship": "tàu",
    "govt văn phòng": "cơ quan nhà nước",
    "cảnh sát ga": "đồn",
    "cũ lần": "xưa",
    "cũ things": "đồ cũ",
    "burst mở": "nổ tung",
    "rise trên": "dâng",
    "be caught": "bị bắt",
    "gather (contributions)": "kêu góp",
    "pack trên": "gói",
    "rời with": "gửi",
    "rời to": "ra đi",
    "second thời gian": "lần hai",
    "phường off · bảo vệ": "phòng vệ",
    "làm tốt": "bổ sung",
    "về to": "phục hồi",
    "cầm miệng": "ngậm",
    "chịu tâm": "chịu đựng",
    "được thin": "mỏng",
    "đầy tháng · -ship": "rằm",
    "nút giao thông · thời kỳ": "giao thời",
    "dài thời gian · cũ story": "lâu / chuyện xưa",
    "trẻ animals": "thú con",
    "inverted": "đảo",
    "emulate": "thi đua",
    "jammed": "kẹt",
    "leader": "thủ lĩnh",
    "trade": "thương mại",
    "attire": "trang phục",
    "navigate": "hàng hải",
    "prohibition": "cấm",
    "con dấu": "con dấu",
    "plant": "trồng",
    "level": "mức",
    "pressure": "áp lực",
    "expand": "mở rộng",
    "halt": "dừng",
    "waves": "sóng",
    "sash": "đai",
    "prolong": "kéo dài",
    "feathers": "lông vũ",
    "harden": "cứng",
    "abbreviation": "viết tắt",
    "acquiesce": "cam chịu",
    "boulder": "tảng đá",
    "practice": "luyện",
    "lightly": "nhẹ",
    "castle": "thành",
    "afflicted": "mắc bệnh",
    "ấn bản": "bản in",
    "exploits": "công trạng",
    "freight": "hàng hóa",
    "mix": "trộn",
    "pond": "ao",
    "seasons": "mùa",
    "star": "sao",
    "document": "tài liệu",
    "warehouse": "kho",
    "statue": "tượng",
    "incense": "hương",
    "slope": "dốc",
    "linen": "vải lanh",
    "quake": "rung",
    "reliant": "dựa vào",
    "enroll": "ghi danh",
    "sheet": "tấm",
    "duplicate": "bản sao",
    "mail": "thư",
    "lean": "nghiêng",
    "burn": "đốt",
    "tracks": "dấu vết",
    "employ": "thuê",
    "exchange": "đổi",
    "bake": "nướng",
    "simplicity": "giản dị",
    "entrails": "nội tạng",
    "pair": "đôi",
    "thorn": "gai",
    "cheerful": "vui vẻ",
    "fishing": "đánh cá",
    "stiff": "cứng",
    "sack": "bao",
    "bathe": "tắm",
    "juvenile": "trẻ",
    "bosom": "ngực",
    "arm": "cánh tay",
    "revered": "tôn kính",
    "celebrate": "chúc mừng",
    "fluid": "chất lỏng",
    "garment": "áo",
    "shoulder": "vai",
    "zero": "không",
    "infancy": "ấu thơ",
    "yellow": "vàng",
    "sweet": "ngọt",
    "cloud": "mây",
    "dig": "đào",
    "soft": "mềm",
    "frozen": "đóng băng",
    "outskirts": "ngoại ô",
    "loins": "eo",
    "charcoal": "than",
    "dry": "khô",
    "insect": "côn trùng",
    "melt": "tan",
    "mineral": "khoáng",
    "grandchild": "cháu",
    "paint": "sơn",
    "flats": "nhà phố",
    "poison": "độc",
    "shout": "hét",
    "worship": "thờ",
    "icicle": "nước đá",
    "rod": "gậy",
    "pray": "cầu",
    "flour": "bột",
    "thread": "sợi",
    "cotton": "bông",
    "sweat": "mồ hôi",
    "copper": "đồng",
    "damp": "ẩm",
    "bottle": "chai",
    "blossom": "nở",
    "tin can": "lon",
    "fat": "mỡ",
    "steam": "hơi",
    "till": "cày",
    "corner": "góc",
    "barley": "lúa mạch",
    "nose": "mũi",
    "part speech": "từ loại",
    "stomach": "dạ dày",
    "laundry": "giặt",
    "pagoda": "tháp",
    "ashes": "tro",
    "cap": "mũ",
    "shellfish": "sò",
    "dish": "đĩa",
    "agreement": "đồng ý",
    "livestock": "gia súc",
    "pinch": "kẹp",
    "overall": "toàn thể",
    "tie": "buộc",
    "fundamentals": "nền tảng",
    "wisteria": "tử đằng",
    "swamp": "đầm",
    "evidence": "bằng chứng",
    "unfold": "mở ra",
    "attitude": "thái độ",
    "single": "đơn",
    "defense": "phòng vệ",
    "accusation": "cáo buộc",
    "stocks": "cổ phiếu",
    "evaluate": "đánh giá",
    "shadow": "bóng",
    "pine cây": "thông",
    "nucleus": "hạt nhân",
    "dissolve": "hòa tan",
    "made": "chế",
    "conjecture": "suy đoán",
    "utensil": "dụng cụ",
    "promontory": "mũi đất",
    "impart": "truyền",
    "detach": "tách",
    "lineage": "dòng dõi",
    "con trai": "con trai",
    "healthy": "khỏe",
    "alliance": "liên minh",
    "accompany": "đi cùng",
    "weave": "dệt",
    "broaden": "mở rộng",
    "shake": "lắc",
    "valve": "van",
    "stern": "nghiêm",
    "fiber": "sợi",
    "bases": "căn cứ",
    "elementary": "cơ bản",
    "confront": "đối đầu",
    "imitation": "bắt chước",
    "masculine": "nam",
    "tense": "căng",
    "abolish": "bãi bỏ",
    "creek": "lạch",
    "boom": "hưng thịnh",
    "emperor": "hoàng đế",
    "step": "bước",
    "bond": "trái phiếu",
    "entertain": "mừng",
    "inherit": "thừa kế",
    "muscle": "cơ",
    "interment": "an táng",
    "apprehend": "bắt",
    "beguile": "mê hoặc",
    "listen": "nghe",
    "tighten": "thắt",
    "tassel": "tua",
    "remove": "gỡ",
    "choose": "chọn",
    "excel": "xuất sắc",
    "bullet": "đạn",
    "foothold": "bàn đạp",
    "secret": "bí mật",
    "hillock": "gò",
    "winding": "cuốn",
    "miss": "mất",
    "consort": "bạn lữ",
    "belong": "thuộc",
    "prudence": "thận trọng",
    "frame": "khung",
    "slacken": "nới",
    "subscription": "đặt mua",
    "brandish": "vung",
    "allot": "cấp",
    "deer": "hươu",
    "fare": "cước",
    "county": "quận",
    "char": "cháy sém",
    "disaster": "thảm họa",
    "bay": "vịnh",
    "chop": "chặt",
    "defer": "nhường",
    "settlement": "thanh toán",
    "stimulate": "thúc",
    "humility": "khiêm",
    "astringent": "chát",
    "maneuver": "điều khiển",
    "portable": "cầm tay",
    "checkup": "khám",
    "consign": "ủy thác",
    "snapshot": "chụp",
    "nativity": "ra đời",
    "encroach": "xâm",
    "transparent": "trong suốt",
    "haven": "bến",
    "split": "nứt",
    "cleverness": "nhanh trí",
    "strict": "chặt",
    "turf": "cỏ",
    "congratulations": "chúc mừng",
    "handle": "xử lý",
    "sue": "kiện",
    "commandment": "giới luật",
    "welfare": "phúc lợi",
    "delight": "hoan hỉ",
    "persuade": "khuyên",
    "straw rope": "thừng rơm",
    "excuse": "tha",
    "recommend": "tiến cử",
    "neighboring": "láng giềng",
    "pattern": "khuôn",
    "benevolence": "đức",
    "cedar": "tuyết tùng",
    "explanation": "giải thích",
    "intimidate": "uy",
    "stagnate": "đọng",
    "hump": "gò",
    "godown": "kho",
    "lad": "cậu",
    "liver": "gan",
    "exquisite": "tinh xảo",
    "africa": "châu Phi",
    "cord": "dây",
    "sincerity": "thành",
    "haiku": "haiku",
    "wonder": "kinh ngạc",
    "hemp": "gai dầu",
    "plum": "mận",
    "rapids": "ghềnh",
    "purport": "ý thú",
    "hermit": "tiên",
    "consolation": "an ủi",
    "holy": "thánh",
    "delicious": "ngon",
    "instant": "tức thì",
    "willow": "liễu",
    "falsehood": "giả",
    "threaten": "đe dọa",
    "sacrifice": "hy sinh",
    "flag": "cờ",
    "netting": "lưới",
    "dragon": "rồng",
    "lagoon": "đầm phá",
    "enemy": "địch",
    "fascination": "mê hoặc",
    "acid": "axit",
    "destroy": "diệt",
    "cornerstone": "nền móng",
    "rot": "thối",
    "skids": "chân đỡ",
    "cherry": "anh đào",
    "slippery": "trơn",
    "orphan": "mồ côi",
    "inflammation": "viêm",
    "phrase": "cụm",
    "steel": "thép",
    "stubborn": "bướng",
    "encourage": "khích lệ",
    "axis": "trục",
    "wink": "nháy mắt",
    "cannon": "pháo",
    "boast": "khoe",
    "tempt": "xúi",
    "thwart": "cản",
    "ditch": "mương",
    "strangle": "bóp",
    "solely": "duy",
    "dart": "mũi tên",
    "-proof": "chịu",
    "fierce": "dữ",
    "perfume": "hương",
    "penal": "trừng",
    "sabre": "kiếm",
    "chess piece": "quân cờ",
    "constancy": "hằng",
    "ethics": "luân lý",
    "exhibit": "bày",
    "humanity": "nhân",
    "overcome": "khắc",
    "outline": "khái quát",
    "arrest": "bắt",
    "grave": "mộ",
    "atmosphere": "không khí",
    "tortoise": "rùa",
    "hearth": "lò",
    "breed": "chăn",
    "particularly": "đặc biệt",
    "hole": "lỗ",
    "strange": "lạ",
    "ridicule": "kiêu",
    "crane": "sếu",
    "warmth": "ấm",
    "tolerant": "khoan dung",
    "capsize": "lật",
    "placenta": "nhau",
    "cry": "khóc",
    "lungs": "phổi",
    "upright": "trinh",
    "peaceful": "yên",
    "shade": "bóng râm",
    "ardent": "mãnh liệt",
    "draft": "thảo",
    "hill": "đồi",
    "ridgepole": "đòn nóc",
    "cartoon": "truyện tranh",
    "sticky": "dính",
    "enlightenment": "ngộ",
    "grace": "ơn",
    "beans": "đậu",
    "consummate": "hoàn tất",
    "lunatic": "điên",
    "highness": "bệ hạ",
    "cultivate": "vun",
    "decline": "suy",
    "yield": "khuất",
    "thin": "nhạt",
    "pluck": "nhổ",
    "quasi-": "chuẩn",
    "exhort": "khuyến",
    "immersed": "ngấm",
    "surplus": "dư",
    "gall bladder": "mật",
    "void": "hư",
    "spirits": "linh",
    "repent": "hối",
    "rebuke": "răn",
    "wretched": "thảm",
    "tyrannize": "ngược đãi",
    "flip": "lật",
    "set": "đặt",
    "gradually": "từ từ",
    "shield": "khiên",
    "rut": "vết xe",
    "bag": "bao",
    "disturb": "cản",
    "grate": "cọ",
    "whale": "cá voi",
    "villa": "biệt thự",
    "consent": "ưng",
    "thunder": "sấm",
    "drift": "trôi",
    "feelings": "cảm xúc",
    "plantation": "trồng",
    "kidnap": "bắt cóc",
    "annexed": "kèm",
    "crown": "mũ miện",
    "diagonal": "chéo",
    "mirror": "gương",
    "wandering": "lang thang",
    "lie": "dối",
    "podium": "bục",
    "purple": "tím",
    "dawn": "rạng đông",
    "wholesale": "sỉ",
    "deviate": "lạc",
    "horizon": "chân trời",
    "prison": "ngục",
    "esteem": "còn",
    "carve": "chạm",
    "appear": "hiện",
    "adroit": "khéo",
    "deceit": "lừa",
    "solemn": "nghiêm",
    "chestnut": "hạt dẻ",
    "foolish": "ngu",
    "applaud": "khen",
    "ghost": "quỷ",
    "princess": "công chúa",
    "vow": "thề",
    "grasp": "nắm",
    "tread": "bước",
    "alienate": "sơ",
    "sturdy": "cứng cỏi",
    "rapidly": "mau",
    "subjugate": "chinh",
    "marry into": "lấy chồng",
    "empress": "hoàng hậu",
    "germ": "vi khuẩn",
    "sickle": "liềm",
    "nest": "tổ",
    "repeatedly": "thường xuyên",
    "harp": "đàn cầm",
    "shelf": "kệ",
    "cruel": "tàn",
    "loneliness": "tịch",
    "vulgar": "tục",
    "wicked": "tà",
    "tranquilize": "trấn",
    "inferiority": "kém",
    "assault": "đánh",
    "pavilion": "đình",
    "suspicious": "quái",
    "pigeon": "bồ câu",
    "pity": "tiếc",
    "harvest": "gặt",
    "destitution": "thiếu",
    "mulberry": "dâu",
    "marrow": "tủy",
    "basin": "chậu",
    "robust": "tráng",
    "dike": "đê",
    "hungry": "đói",
    "epidemic": "dịch",
    "stupid": "si",
    "conveyor": "chuyển",
    "healing": "chữa",
    "paulownia": "ngô đồng",
    "enclosure": "thành quách",
    "urine": "nước tiểu",
    "spit": "nhổ",
    "hawk": "diều hâu",
    "captive": "tù binh",
    "pottery": "gốm",
    "bell": "chuông",
    "remorse": "hận",
    "boar": "heo rừng",
    "magnet": "từ",
    "coarse": "thô",
    "bud": "mầm",
    "umbrella": "ô",
    "industry": "cần mẫn",
    "equestrian": "kỵ",
    "sequential": "tuần hoàn",
    "neglect": "lười",
    "dormitory": "ký túc xá",
    "phoenix": "phượng",
    "congeal": "đông",
    "seedling": "cây non",
    "animal": "thú",
    "pathetic": "ai",
    "droop": "rủ",
    "snake": "rắn",
    "sew": "may",
    "span": "trải",
    "gutter": "rãnh",
    "confused": "lộn xộn",
    "bamboo grass": "sasa",
    "cereals": "ngũ cốc",
    "mausoleum": "lăng",
    "fog": "sương mù",
    "queen": "hoàng hậu",
    "starve": "đói",
    "stinking": "hôi",
    "ecstasy": "vui sướng",
    "truss": "trói",
    "calendar": "lịch",
    "blind": "mù",
    "embarrass": "nhục",
    "control": "quản",
    "monkey": "khỉ",
    "deluge": "lụt",
    "sated": "no",
    "superfluous": "thừa",
    "peach": "đào",
    "hunt": "săn",
    "whirlpool": "xoáy",
    "forge": "rèn",
    "sword": "đao",
    "drum": "trống",
    "naked": "trần",
    "furthermore": "vẫn",
    "clod": "cục",
    "bow": "cung",
    "membrane": "màng",
    "fan": "quạt",
    "intestines": "ruột",
    "vat": "bồn",
    "mercy": "từ",
    "pickling": "muối",
    "tomb": "mộ",
    "camellia": "trà hoa",
    "tongue": "lưỡi",
    "gorge": "hẻm",
    "summit": "đỉnh",
    "lotus": "sen",
    "condolences": "phúng",
    "latter": "ất",
    "soup": "canh",
    "nun": "ni",
    "equilibrium": "cân bằng",
    "sheep": "cừu",
    "review": "duyệt",
    "spy": "thám",
    "hoarse": "khàn",
    "daring": "dám",
    "womb": "thai",
    "fermentation": "lên men",
    "pork": "thịt lợn",
    "intercept": "chặn",
    "sulphur": "lưu huỳnh",
    "pardon": "tha",
    "bubbles": "bọt",
    "again": "lại",
    "rue": "than",
    "obese": "béo",
    "mourning": "kỵ",
    "voiced": "đục",
    "orchid": "lan",
    "swift": "mau",
    "resemblance": "giống",
    "decay": "mục",
    "husk": "vỏ",
    "mediator": "môi giới",
    "zen": "thiền",
    "transfer": "chuyển",
    "insert": "cắm",
    "storm": "bão",
    "chinquapin": "dẻ",
    "obeisance": "hầu",
    "sail": "buồm",
    "daybreak": "bình minh",
    "greatness": "kiệt xuất",
    "lock": "khóa",
    "fist": "nắm đấm",
    "soar": "bay",
    "bungling": "vụng",
    "beginning": "khởi",
    "uncle": "chú",
    "feminine": "cái",
    "pass through": "hanh thông",
    "confer": "ban",
    "vinegar": "giấm",
    "versify": "ngâm",
    "relay": "tiếp",
    "peak": "đỉnh",
    "headland": "mũi đất",
    "reef": "đá ngầm",
    "from": "từ",
    "twig": "cành",
    "matrimony": "hôn nhân",
    "rock": "đá",
    "lips": "môi",
    "intimate": "hòa mục",
    "leisure": "nhàn",
    "barbarian": "rợ",
    "lowly": "hèn",
    "casting": "đúc",
    "rub": "xoa",
    "slave": "nô",
    "calamity": "họa",
    "stalk": "thân",
    "commander": "thống soái",
    "vapor": "hơi nước",
    "banana": "chuối",
    "precious stone": "lưu ly",
    "diarrhea": "lỵ",
    "pit": "hố",
    "indigo": "chàm",
    "burglar": "giặc",
    "squeeze": "ép",
    "paddy ridge": "bờ ruộng",
    "cavity": "lỗ",
    "spine": "cột sống",
    "torture": "tra tấn",
    "southeast": "đông nam",
    "woods": "rừng",
    "discreet": "cẩn thận",
    "kiln": "lò nung",
    "martyrdom": "tuẫn",
    "censure": "hặc",
    "degenerate": "sa đọa",
    "scaffold": "giàn",
    "bridegroom": "rể",
    "captured": "tù",
    "rainbow": "cầu vồng",
    "ooze": "rỉ",
    "steadily": "dần",
    "mosquito": "muỗi",
    "hollyhock": "cẩm quỳ",
    "seaweed": "rong",
    "fief": "lộc",
    "menacing": "hăm dọa",
    "convex": "lồi",
    "stretch": "duỗi",
    "frost": "sương giá",
    "nitrate": "nitrat",
    "parsley": "cần tây",
    "apricot": "mơ",
    "coffin": "quan tài",
    "confucian": "nho",
    "fragrant": "thơm",
    "watchtower": "lầu",
    "eyebrow": "lông mày",
    "fuel": "củi",
    "brown": "nâu",
    "steep": "dốc",
    "darning": "vá",
    "plug": "nút",
    "hazelnut": "phỉ",
    "concave": "lõm",
    "vine": "dây leo",
    "tempering": "luyện",
    "falcon": "cắt",
    "chick": "gà con",
    "kindness": "ơn",
    "delusion": "vọng",
    "only": "chỉ",
    "comet": "sao chổi",
    "mimeograph": "sao chép",
    "heir": "người thừa kế",
    "nursing": "chăm",
    "furrow": "luống",
    "refreshing": "sảng",
    "lazy": "lười",
    "recollect": "nhớ",
    "license": "cho phép",
    "marquis": "hầu",
    "sow seeds": "gieo",
    "carp": "chép",
    "arc": "cung",
    "sparkle jewelry": "lấp lánh",
    "affixed": "gắn",
    "however": "nhưng",
    "taro": "khoai",
    "scarlet": "đỏ thắm",
    "citron": "thanh yên",
    "cocoon": "kén",
    "brilliant": "rực",
    "mountains towering in a row": "núi trùng điệp",
    "washing": "rửa",
    "dilate": "phình",
    "also": "cũng",
    "melting": "luyện kim",
    "moreover": "và lại",
    "decrease": "hao",
    "model": "nặn",
    "intelligence": "minh mẫn",
    "friendship": "tình",
    "descendent": "dòng dõi",
    "jasmine": "nhài",
    "maple": "phong",
    "violet": "hoa tím",
    "pox": "đậu mùa",
    "edify": "khai hóa",
    "eggplant": "cà",
    "treetops": "ngọn cây",
    "iris": "diên vĩ",
    "glassy": "trong như thủy tinh",
    "smiling": "mỉm cười",
    "rise": "vang",
    "gauze": "sa",
    "eulogy": "tụng",
    "excessive": "lạm",
    "holly": "nhựa ruồi",
    "actor": "kép",
    "tedious": "dông dài",
    "victory": "thắng",
    "lotus": "sen",
    "burn": "đốt",
}

WORD = {
    "tall": "cao", "out": "ra", "in": "trong", "off": "tắt", "over": "xong",
    "along": "dọc", "former": "trước", "main": "chính", "set": "đặt",
    "paddy": "ruộng", "charge": "phụ trách", "business": "công việc",
    "sell": "bán", "fee": "phí", "hurry": "vội", "ill": "bệnh", "test": "kiểm tra",
    "flavor": "vị", "borrow": "mượn", "weekday": "ngày thường", "lend": "cho mượn",
    "chamber": "phòng", "boiled": "luộc", "exertion": "gắng", "cow": "bò",
    "elect": "bầu", "sutra": "kinh", "utmost": "tột", "inter-": "tương",
    "sino-": "Hán", "western": "Tây", "radical": "bộ", "counter": "loại từ",
    "stroke": "nét", "odd": "lẻ", "rat": "chuột", "oneself": "bản thân",
    "album": "tập ảnh", "sofa": "ghế sofa", "dyer": "thợ nhuộm", "beer": "bia",
    "video": "video", "wine": "rượu vang", "poem": "thơ", "poet": "nhà thơ",
    "lawn": "bãi cỏ", "week": "tuần", "boys": "con trai", "pine": "thông",
    "tree": "cây", "nest": "tổ", "sun": "mặt trời", "peas": "đậu", "verb": "động từ",
    "road": "đường", "horse": "ngựa", "plum": "mận", "lap": "vòng", "knee": "đầu gối",
    "cord": "dây", "tale": "câu chuyện", "tomb": "mộ", "call": "gọi", "rich": "giàu",
    "daze": "mê", "fog": "sương mù", "mug": "cốc", "mail": "thư", "gist": "điểm chính",
    "nude": "trần", "ring": "vòng", "tear": "nước mắt", "cage": "lồng", "yawn": "ngáp",
    "gang": "băng đảng", "dial": "quay số", "pink": "hồng", "menu": "thực đơn",
    "running": "chạy bộ", "lens": "thấu kính", "lump": "cục", "husk": "vỏ", "gas": "khí",
    "zone": "khu", "comb": "lược", "form": "hình thức", "item": "mục",
    "sashimi": "sashimi", "gear": "bánh răng", "lips": "môi", "myth": "thần thoại",
    "wire": "dây", "hydro": "hydro", "flask": "bình", "essays": "tùy bút",
    "integer": "số nguyên", "equator": "xích đạo", "cork": "nút", "sandals": "dép",
    "funeral": "đám tang", "postage": "cước", "tabi": "tất tabi", "drum": "trống",
    "ellipse": "elip", "lending": "cho mượn", "pronoun": "đại từ", "bamboo": "tre",
    "siesta": "ngủ trưa", "carving": "chạm khắc", "claw": "móng", "razor": "dao cạo",
    "nail": "đinh", "farm": "nông trại", "nausea": "buồn nôn", "orient": "phương Đông",
    "theft": "trộm", "teacup": "tách trà", "scratch": "cào", "route": "lộ trình",
    "forte": "sở trường", "rainbow": "cầu vồng", "sunrise": "bình minh",
    "shadow": "bóng", "scales": "cân", "firing": "bắn", "radius": "bán kính",
    "sarcasm": "châm biếm", "elbow": "khuỷu", "writer": "tác giả", "binding": "bìa",
    "spread": "lan", "balloon": "bóng bay", "adverb": "trạng từ", "plural": "số nhiều",
    "context": "ngữ cảnh", "sailor": "thủy thủ", "hiragana": "hiragana",
    "katakana": "katakana", "closure": "bế mạc", "editing": "biên tập", "web": "mạng",
    "hygiene": "vệ sinh", "packing": "đóng gói", "bandage": "băng", "dialect": "phương ngữ",
    "meadow": "đồng cỏ", "pillow": "gối", "plain": "trơn", "noun": "danh từ",
    "niece": "cháu gái", "wood": "gỗ", "mailing": "gửi thư", "vessel": "bình",
    "lava": "dung nham", "greed": "tham", "yukata": "yukata", "grain": "hạt",
    "hostel": "ký túc", "consul": "lãnh sự", "brick": "gạch", "candle": "nến",
    "pun": "chơi chữ", "alkali": "kiềm", "hour": "giờ", "encore": "bis",
    "errand": "việc vặt", "cocktail": "cocktail", "cheat": "gian lận",
    "career": "sự nghiệp", "quiz": "đố", "club": "câu lạc bộ", "graph": "đồ thị",
    "contest": "cuộc thi", "compass": "la bàn", "jazz": "jazz", "jumbo": "khổng lồ",
    "genre": "thể loại", "shock": "sốc", "studio": "studio", "slacks": "quần âu",
    "jelly": "thạch", "solo": "đơn ca", "dozen": "tá", "typist": "thư ký đánh máy",
    "timer": "hẹn giờ", "timing": "thời điểm", "tile": "gạch ốp", "dump": "đổ",
    "chime": "chuông", "spoil": "cưng chiều", "dessert": "tráng miệng", "telex": "telex",
    "transistor": "transistor", "drill": "khoan", "napkin": "khăn ăn",
    "nuance": "sắc thái", "pajamas": "đồ ngủ", "pachinko": "pachinko",
    "badge": "huy hiệu", "bat": "gậy", "hangar": "nhà chứa máy bay", "virus": "virus",
    "hint": "gợi ý", "boots": "ủng", "ferry": "phà", "buzzer": "còi",
    "swing": "đu đưa", "front": "lễ tân", "fawn": "nịnh", "boycott": "tẩy chay",
    "hose": "vòi", "pause": "tư thế", "hall": "sảnh", "volt": "vôn", "pump": "bơm",
    "mark": "nhãn", "massage": "xoa bóp", "mrs": "bà", "maker": "hãng",
    "melody": "giai điệu", "motel": "nhà nghỉ", "rice": "cơm", "label": "nhãn",
    "race": "cuộc đua", "lady": "quý cô", "lever": "cần", "watt": "oát",
    "evil": "ác", "rascal": "đồ xấu", "reed": "sậy", "dark": "tối", "commit": "ủy thác",
    "dissent": "phản đối", "outfit": "trang phục", "swirl": "xoáy", "image": "hình ảnh",
    "hero": "anh hùng", "nephew": "cháu trai", "timbre": "âm sắc", "fossil": "hóa thạch",
    "cattle": "gia súc", "retinue": "gia thần", "rivers": "sông ngòi", "spark": "tia lửa",
    "pollen": "phấn hoa", "load": "hàng", "baling": "đóng gói", "strain": "quá sức",
    "autopsy": "mổ tử thi", "monster": "quái vật", "channel": "eo biển",
    "pioneer": "khai phá", "stories": "tầng", "cliff": "vách đá", "highway": "quốc lộ",
    "kernel": "hạt nhân", "ensure": "đảm bảo", "chin": "cằm", "credit": "ghi nợ",
    "quota": "chỉ tiêu", "funny": "hài", "cheer": "hoan hô", "lenient": "khoan",
    "viewing": "xem", "cancer": "ung thư", "sham": "đồ giả", "comedy": "hài kịch",
    "loom": "khung cửi", "whim": "thất thường", "prayer": "lời cầu", "orbit": "quỹ đạo",
    "forgery": "giả mạo", "truce": "đình chiến", "palace": "cung điện",
    "poverty": "nghèo", "veto": "phủ quyết", "forcing": "cưỡng", "threat": "đe dọa",
    "arousal": "hưng phấn", "labor": "lao động", "taboo": "kiêng", "myopia": "cận thị",
    "testing": "thẩm", "grumble": "cằn nhằn", "blank": "trống", "vacancy": "chỗ trống",
    "hunger": "đói", "bending": "khúc xạ", "mob": "đám đông", "details": "chi tiết",
    "cost": "chi phí", "meter": "đồng hồ đo", "warning": "cảnh giác", "scorn": "khinh",
    "rash": "hấp tấp", "troupe": "đoàn kịch", "crystal": "tinh thể", "reward": "treo giải",
    "omiai": "xem mặt", "hearsay": "lời nhắn", "groin": "háng", "retreat": "rút",
    "words": "cụm từ", "polish": "đánh bóng", "licence": "công nhận", "oral": "miệng",
    "dirt": "cặn", "protest": "phản đối", "subsidy": "khấu trừ", "pose": "tư thế",
    "act": "hành vi", "march": "diễu hành", "spices": "gia vị", "plateau": "cao nguyên",
    "inform": "báo", "realm": "lãnh thổ", "curio": "đồ cổ", "trifle": "chuyện nhỏ",
    "deduct": "trừ", "gravel": "sỏi", "fraud": "lừa đảo", "mining": "khai thác",
    "riches": "của cải", "fence": "hàng rào", "murder": "giết người",
    "shamisen": "shamisen", "thought": "suy nghĩ", "mandate": "chỉ thị",
    "orders": "mệnh lệnh", "bestow": "ban", "raising": "nuôi", "samurai": "samurai",
    "self": "cái tôi", "hubris": "kiêu", "spin": "tự quay", "essence": "thực chất",
    "sod": "cỏ", "weaken": "làm yếu", "swap": "đổi", "trouble": "công",
    "choker": "vòng cổ", "returns": "doanh thu", "seating": "chứa", "circuit": "vòng",
    "beast": "thú", "lessons": "lớp học thêm", "sailing": "xuất phát",
    "owning": "mang theo", "retail": "bán lẻ", "palm": "lòng bàn tay",
    "treetop": "ngọn cây", "erasing": "xóa", "reflect": "tự xét", "symbol": "biểu tượng",
    "boss": "cấp trên", "pact": "điều ước", "cane": "gậy", "colony": "thuộc địa",
    "fabric": "vải", "devotee": "tín đồ", "outset": "xuất phát", "pearl": "ngọc trai",
    "mystery": "huyền bí", "gesture": "cử chỉ", "hostage": "con tin",
    "glimpse": "ánh mắt người", "dustpan": "đồ hốt rác", "guess": "phỏng đoán",
    "cult": "sùng bái", "numeral": "số từ", "equip": "lắp", "install": "lắp đặt",
    "mount": "gắn", "fruits": "thành quả", "pure": "trong", "menses": "kinh nguyệt",
    "bible": "kinh thánh", "recipe": "cách làm", "honest": "thành thực",
    "youth": "tuổi trẻ", "repose": "tĩnh", "static": "tĩnh", "deficit": "thâm hụt",
    "despair": "tuyệt vọng", "tactics": "chiến thuật", "mean": "hèn", "dye": "nhuộm",
    "pierce": "thấm", "diving": "lặn", "fibre": "sợi", "booking": "bán trước",
    "virtue": "thiện", "hatred": "hận", "saliva": "nước bọt", "giving": "nhượng bộ",
    "cope": "đối phó", "default": "nợ đọng", "thigh": "đùi", "mess": "hỏng",
    "shit": "phân", "ordinal": "thứ", "litter": "cáng", "sigh": "than",
    "carbon": "cacbon", "tanka": "tanka", "protein": "protein", "terrain": "địa hình",
    "hell": "địa ngục", "slack": "chùng", "lag": "chậm", "damn": "đồ súc sinh",
    "store": "tích", "launch": "bắt tay", "libel": "phỉ báng", "pivot": "trung khu",
    "raffle": "bốc thăm", "tide": "thủy triều", "guts": "ruột", "chief": "thủ trưởng",
    "spire": "đỉnh", "sinking": "chìm", "wages": "tiền lương", "tsunami": "sóng thần",
    "falling": "rơi", "pursuit": "truy", "exile": "trục xuất", "strap": "tay nắm",
    "like": "giống", "tea": "trà", "mud": "bùn", "ice": "nước đá", "gem": "ngọc",
    "phd": "tiến sĩ", "ton": "tấn", "add": "cộng", "continue": "tiếp tục",
    "scribe": "ghi", "lively": "sống động", "unravel": "tháo", "yonder": "kia",
    "revelation": "báo", "anti-": "phản", "judgement": "phán", "acknowledge": "thừa nhận",
    "affair": "vụ", "pull": "kéo", "argument": "luận", "sex": "tính", "task": "vụ",
    "first": "đầu", "times": "lần", "esq": "ngài", "stab": "đâm", "department": "khoa",
    "other": "khác", "dispose": "xử", "quick": "nhanh", "fly": "bay", "kill": "giết",
    "blame": "trách", "catch": "bắt", "suffering": "khổ", "crowded": "chật",
    "permit": "cho phép", "convenience": "tiện", "scatter": "rải", "marriage": "kết hôn",
    "floating": "nổi", "diligence": "chăm", "miscellaneous": "tạp", "beckon": "vẫy",
    "quandary": "khốn", "lack": "thiếu", "approve": "tán thành",
    "longing": "khát", "laugh": "cười", "mutually": "lẫn nhau", "bundle": "bó",
    "escape": "trốn", "astray": "lạc", "closed": "đóng", "grass": "cỏ", "sake": "rượu",
    "steal": "trộm", "suck": "hút", "sunshine": "nắng", "honorable": "kính",
    "tooth": "răng", "forget": "quên", "mistake": "nhầm", "wash": "rửa",
    "salute": "lễ", "angry": "giận", "swim": "bơi", "ancestor": "tổ",
    "exhausted": "mệt", "abdomen": "bụng", "smoke": "khói", "dreadful": "sợ",
    "box": "hộp", "busy": "bận", "shoes": "giày", "shame": "xấu hổ",
    "admirable": "vĩ", "mèo": "mèo", "co-": "cùng", "jurisdiction": "khu hạt",
    "prefecture": "tỉnh", "establishment": "thiết lập", "investigate": "điều tra",
    "leather": "da", "forces": "thế", "dwindle": "giảm", "agriculture": "nông nghiệp",
    "range": "vùng", "forehead": "trán", "europe": "châu Âu", "semi-": "bán",
    "environs": "ven", "incur": "chịu", "lower": "thấp", "individual": "cá nhân",
    "gate": "cổng", "chapter": "môn", "brain": "não", "extreme": "cực",
    "condition": "tình hình", "needle": "kim", "specialty": "chuyên", "valley": "thung lũng",
    "storey": "tầng", "touch": "tiếp", "gulf": "vịnh", "record": "ghi",
    "circumference": "chu vi", "ticket": "vé", "compilation": "biên", "transcend": "vượt",
    "row": "hàng", "heal": "chữa", "marketing": "bán", "prohibition": "cấm",
    "short": "ngắn", "oil": "dầu", "fortune-telling": "bói", "plant": "trồng",
    "halt": "dừng", "feathers": "lông", "harden": "cứng lại", "thick": "dày",
    "age": "tuổi", "blood": "máu", "warm": "ấm", "hope": "hy vọng",
    "dirty": "bẩn", "bone": "xương", "weak": "yếu", "group": "nhóm",
    "salt": "muối", "sand": "cát", "hair": "tóc", "floor": "sàn",
    "egg": "trứng", "lake": "hồ", "milk": "sữa", "dry": "khô",
    "insect": "côn trùng", "poison": "độc", "ice": "băng",
    "green": "xanh lá", "red": "đỏ", "blue": "xanh", "black": "đen",
    "white": "trắng", "yellow": "vàng", "spring": "xuân", "summer": "hè",
    "autumn": "thu", "winter": "đông", "morning": "sáng", "night": "đêm",
    "today": "hôm nay", "tomorrow": "ngày mai", "yesterday": "hôm qua",
    "father": "bố", "mother": "mẹ", "friend": "bạn", "child": "con",
    "man": "nam", "woman": "nữ", "person": "người", "people": "người",
    "water": "nước", "fire": "lửa", "earth": "đất", "gold": "vàng",
    "tree": "cây", "mountain": "núi", "river": "sông", "sun": "mặt trời",
    "moon": "mặt trăng", "star": "sao", "sky": "trời", "rain": "mưa",
    "wind": "gió", "snow": "tuyết", "flower": "hoa", "fish": "cá",
    "bird": "chim", "dog": "chó", "cat": "mèo", "horse": "ngựa",
    "time": "thời gian", "year": "năm", "month": "tháng", "day": "ngày",
    "hour": "giờ", "minute": "phút", "week": "tuần", "now": "bây giờ",
    "before": "trước", "after": "sau", "up": "trên", "down": "dưới",
    "left": "trái", "right": "phải", "inside": "trong", "outside": "ngoài",
    "east": "đông", "west": "tây", "south": "nam", "north": "bắc",
    "big": "lớn", "small": "nhỏ", "high": "cao", "low": "thấp",
    "new": "mới", "old": "cũ", "good": "tốt", "bad": "xấu",
    "hot": "nóng", "cold": "lạnh", "long": "dài", "short": "ngắn",
    "many": "nhiều", "few": "ít", "go": "đi", "come": "đến",
    "see": "nhìn", "hear": "nghe", "eat": "ăn", "drink": "uống",
    "buy": "mua", "sell": "bán", "read": "đọc", "write": "viết",
    "speak": "nói", "think": "nghĩ", "know": "biết", "learn": "học",
    "work": "làm", "play": "chơi", "sleep": "ngủ", "walk": "đi bộ",
    "run": "chạy", "stand": "đứng", "sit": "ngồi", "open": "mở",
    "close": "đóng", "begin": "bắt đầu", "end": "kết thúc", "stop": "dừng",
    "give": "cho", "take": "lấy", "get": "được", "make": "làm",
    "use": "dùng", "help": "giúp", "wait": "đợi", "live": "sống",
    "die": "chết", "love": "yêu", "like": "thích", "hate": "ghét",
    "school": "trường", "book": "sách", "house": "nhà", "home": "nhà",
    "car": "xe", "road": "đường", "city": "thành phố", "town": "thị trấn",
    "village": "làng", "country": "nước", "world": "thế giới",
    "company": "công ty", "work": "việc", "money": "tiền", "name": "tên",
    "word": "từ", "language": "ngôn ngữ", "voice": "giọng", "sound": "âm",
    "music": "nhạc", "picture": "tranh", "movie": "phim", "color": "màu",
    "place": "nơi", "life": "sống", "heart": "tim", "mind": "tâm",
    "power": "sức", "force": "lực", "law": "luật", "rule": "quy tắc",
    "true": "thật", "false": "sai", "correct": "đúng", "beautiful": "đẹp",
    "strong": "mạnh", "fast": "nhanh", "slow": "chậm", "early": "sớm",
    "late": "muộn", "near": "gần", "far": "xa", "wide": "rộng",
    "narrow": "hẹp", "deep": "sâu", "light": "nhẹ", "heavy": "nặng",
    "bright": "sáng", "dark": "tối", "clean": "sạch", "full": "đầy",
    "empty": "trống", "young": "trẻ", "same": "giống", "different": "khác",
    "important": "quan trọng", "necessary": "cần thiết", "possible": "có thể",
    "easy": "dễ", "difficult": "khó", "simple": "đơn giản",
    "and": "", "the": "", "of": "", "to": "", "a": "", "an": "",
    "for": "", "with": "", "from": "", "by": "", "as": "", "at": "",
    "or": "", "on": "", "into": "", "about": "", "that": "", "this": "",
    "used": "dùng", "which": "", "e.g.": "", "eg": "", "etc": "v.v.",
    "no": "không", "yes": "có",
}

VI_RE = re.compile(r"[àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]", re.I)
LATIN_WORD = re.compile(r"[A-Za-z][A-Za-z0-9''\-]{1,}")


def load_tsv() -> dict[str, str]:
    out: dict[str, str] = {}
    for p in (ROOT / "scripts").glob("en*.tsv"):
        for line in p.read_text(encoding="utf-8").splitlines():
            if "\t" not in line:
                continue
            a, b = line.split("\t", 1)
            k, v = a.strip().lower(), b.strip()
            if k and v:
                out.setdefault(k, v)
    return out


def clean_noise(s: str) -> str:
    s = re.sub(r"^\(\d+\)\s*", "", s)
    s = re.sub(r"^\d+\.\s*", "", s)
    s = re.sub(r"\s*radical no\.?\s*\d+", "", s, flags=re.I)
    s = re.sub(r"\s*radical \(no\.?\s*\d+\)", "", s, flags=re.I)
    s = re.sub(r"katakana e radical[^.]*", "bộ công", s, flags=re.I)
    s = re.sub(r"\b11pm-1am\b", "23–1 giờ", s, flags=re.I)
    s = re.sub(r"\b1-3am\b", "1–3 giờ", s, flags=re.I)
    s = re.sub(r"\b9-11pm\b", "21–23 giờ", s, flags=re.I)
    s = re.sub(r"\b10\*\*\d+\b", "", s)
    s = re.sub(r"~", "", s)
    s = re.sub(r"\s{2,}", " ", s).strip(" ·,;/")
    return s


def translate_part(part: str, table: dict[str, str]) -> str:
    raw = part.strip()
    if not raw:
        return ""
    cleaned = clean_noise(raw)
    key = re.sub(r"^\(\d+\)\s*", "", cleaned.lower()).strip(" ?.!")
    if key in PHRASE:
        return PHRASE[key]
    if key in table:
        return table[key]
    if key in WORD:
        return WORD[key]
    # word-by-word
    bits = []
    for w in re.split(r"(\s+|/)", cleaned):
        if not w or w.isspace() or w == "/":
            if w == "/":
                bits.append("·")
            elif w.isspace() and bits and bits[-1] != " ":
                bits.append(" ")
            continue
        wl = w.lower().strip(".,;:()!")
        if wl in PHRASE:
            bits.append(PHRASE[wl])
        elif wl in table:
            bits.append(table[wl])
        elif wl in WORD:
            val = WORD[wl]
            if val:
                bits.append(val)
        else:
            bits.append(w)
    out = "".join(bits)
    out = re.sub(r"\s+", " ", out).strip(" ·")
    return out or cleaned


def translate_meaning(meaning: str, table: dict[str, str]) -> str:
    parts = [p.strip() for p in re.split(r"\s*[·|/]\s*", meaning) if p.strip()]
    seen, out = set(), []
    for p in parts:
        nxt = translate_part(p, table)
        nxt = re.sub(r"\s+", " ", nxt).strip(" ·")
        if not nxt:
            continue
        # drop leftover pure-english if we already have vi
        if re.fullmatch(r"[A-Za-z0-9 ,.'()\-]+", nxt) and any(VI_RE.search(x) for x in out):
            mapped = PHRASE.get(nxt.lower()) or table.get(nxt.lower()) or WORD.get(nxt.lower().strip())
            if mapped:
                nxt = mapped
            else:
                continue
        k = nxt.lower()
        if k in seen:
            continue
        seen.add(k)
        out.append(nxt)
    return " · ".join(out[:3]) if out else meaning


def patch_json(path: Path, meaning_idx: int, table: dict[str, str]) -> int:
    rows = json.loads(path.read_text(encoding="utf-8"))
    n = 0
    for r in rows:
        old = r[meaning_idx]
        new = translate_meaning(old, table)
        if new != old:
            r[meaning_idx] = new
            n += 1
    path.write_text(json.dumps(rows, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    return n


def main() -> None:
    table = load_tsv()
    table.update({k: v for k, v in PHRASE.items()})
    nd = patch_json(DICT, 3, table)
    nk = patch_json(KANJI, 3, table)
    print(f"dict patched {nd}, kanji patched {nk}")


if __name__ == "__main__":
    main()
