/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAlphabetRouteImport } from './routes/_app/alphabet'
import { Route as AppDailyRouteImport } from './routes/_app/daily'
import { Route as AppDictionaryRouteImport } from './routes/_app/dictionary'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppFlashcardsRouteImport } from './routes/_app/flashcards'
import { Route as AppGardenRouteImport } from './routes/_app/garden'
import { Route as AppGrammarRouteImport } from './routes/_app/grammar'
import { Route as AppHiraganaRouteImport } from './routes/_app/hiragana'
import { Route as AppKanjiRouteImport } from './routes/_app/kanji'
import { Route as AppKatakanaRouteImport } from './routes/_app/katakana'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppListenRouteImport } from './routes/_app/listen'
import { Route as AppMyWordsRouteImport } from './routes/_app/my-words'
import { Route as AppPathRouteImport } from './routes/_app/path'
import { Route as AppPlayRouteImport } from './routes/_app/play'
import { Route as AppQuizRouteImport } from './routes/_app/quiz'
import { Route as AppRadicalsRouteImport } from './routes/_app/radicals'
import { Route as AppReadRouteImport } from './routes/_app/read'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppRomajiRouteImport } from './routes/_app/romaji'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSongsRouteImport } from './routes/_app/songs'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppVocabularyRouteImport } from './routes/_app/vocabulary'
import { Route as AppDictionaryIndexRouteImport } from './routes/_app/dictionary.index'
import { Route as AppDictionaryIdRouteImport } from './routes/_app/dictionary.$id'
import { Route as AppGrammarIndexRouteImport } from './routes/_app/grammar.index'
import { Route as AppGrammarIdRouteImport } from './routes/_app/grammar.$id'
import { Route as AppHiraganaIndexRouteImport } from './routes/_app/hiragana.index'
import { Route as AppHiraganaIdRouteImport } from './routes/_app/hiragana.$id'
import { Route as AppKanjiIndexRouteImport } from './routes/_app/kanji.index'
import { Route as AppKanjiIdRouteImport } from './routes/_app/kanji.$id'
import { Route as AppKatakanaIndexRouteImport } from './routes/_app/katakana.index'
import { Route as AppKatakanaIdRouteImport } from './routes/_app/katakana.$id'
import { Route as AppPathIndexRouteImport } from './routes/_app/path.index'
import { Route as AppPathIdRouteImport } from './routes/_app/path.$id'
import { Route as AppRadicalsIndexRouteImport } from './routes/_app/radicals.index'
import { Route as AppRadicalsIdRouteImport } from './routes/_app/radicals.$id'
import { Route as AppSongsIndexRouteImport } from './routes/_app/songs.index'
import { Route as AppSongsIdRouteImport } from './routes/_app/songs.$id'
import { Route as AppToolsImportDictionaryRouteImport } from './routes/_app/tools.import-dictionary'
import { Route as AppVocabularyIndexRouteImport } from './routes/_app/vocabulary.index'
import { Route as AppVocabularyIdRouteImport } from './routes/_app/vocabulary.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlphabetRoute = AppAlphabetRouteImport.update({
  id: '/alphabet',
  path: '/alphabet',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyRoute = AppDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AppRoute,
} as any)
const AppDictionaryRoute = AppDictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppGardenRoute = AppGardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => AppRoute,
} as any)
const AppGrammarRoute = AppGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AppRoute,
} as any)
const AppHiraganaRoute = AppHiraganaRouteImport.update({
  id: '/hiragana',
  path: '/hiragana',
  getParentRoute: () => AppRoute,
} as any)
const AppKanjiRoute = AppKanjiRouteImport.update({
  id: '/kanji',
  path: '/kanji',
  getParentRoute: () => AppRoute,
} as any)
const AppKatakanaRoute = AppKatakanaRouteImport.update({
  id: '/katakana',
  path: '/katakana',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppListenRoute = AppListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AppRoute,
} as any)
const AppMyWordsRoute = AppMyWordsRouteImport.update({
  id: '/my-words',
  path: '/my-words',
  getParentRoute: () => AppRoute,
} as any)
const AppPathRoute = AppPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppRadicalsRoute = AppRadicalsRouteImport.update({
  id: '/radicals',
  path: '/radicals',
  getParentRoute: () => AppRoute,
} as any)
const AppReadRoute = AppReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppRomajiRoute = AppRomajiRouteImport.update({
  id: '/romaji',
  path: '/romaji',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSongsRoute = AppSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppVocabularyRoute = AppVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AppRoute,
} as any)
const AppDictionaryIndexRoute = AppDictionaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDictionaryRoute,
} as any)
const AppDictionaryIdRoute = AppDictionaryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDictionaryRoute,
} as any)
const AppGrammarIndexRoute = AppGrammarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGrammarRoute,
} as any)
const AppGrammarIdRoute = AppGrammarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGrammarRoute,
} as any)
const AppHiraganaIndexRoute = AppHiraganaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHiraganaRoute,
} as any)
const AppHiraganaIdRoute = AppHiraganaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHiraganaRoute,
} as any)
const AppKanjiIndexRoute = AppKanjiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKanjiRoute,
} as any)
const AppKanjiIdRoute = AppKanjiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppKanjiRoute,
} as any)
const AppKatakanaIndexRoute = AppKatakanaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKatakanaRoute,
} as any)
const AppKatakanaIdRoute = AppKatakanaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppKatakanaRoute,
} as any)
const AppPathIndexRoute = AppPathIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPathRoute,
} as any)
const AppPathIdRoute = AppPathIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPathRoute,
} as any)
const AppRadicalsIndexRoute = AppRadicalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRadicalsRoute,
} as any)
const AppRadicalsIdRoute = AppRadicalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRadicalsRoute,
} as any)
const AppSongsIndexRoute = AppSongsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSongsRoute,
} as any)
const AppSongsIdRoute = AppSongsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSongsRoute,
} as any)
const AppToolsImportDictionaryRoute =
  AppToolsImportDictionaryRouteImport.update({
    id: '/tools/import-dictionary',
    path: '/tools/import-dictionary',
    getParentRoute: () => AppRoute,
  } as any)
const AppVocabularyIndexRoute = AppVocabularyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVocabularyRoute,
} as any)
const AppVocabularyIdRoute = AppVocabularyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVocabularyRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/alphabet': typeof AppAlphabetRoute
  '/daily': typeof AppDailyRoute
  '/dictionary': typeof AppDictionaryRouteWithChildren
  '/favorites': typeof AppFavoritesRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/garden': typeof AppGardenRoute
  '/grammar': typeof AppGrammarRouteWithChildren
  '/hiragana': typeof AppHiraganaRouteWithChildren
  '/kanji': typeof AppKanjiRouteWithChildren
  '/katakana': typeof AppKatakanaRouteWithChildren
  '/leaderboard': typeof AppLeaderboardRoute
  '/listen': typeof AppListenRoute
  '/my-words': typeof AppMyWordsRoute
  '/path': typeof AppPathRouteWithChildren
  '/play': typeof AppPlayRoute
  '/quiz': typeof AppQuizRoute
  '/radicals': typeof AppRadicalsRouteWithChildren
  '/read': typeof AppReadRoute
  '/review': typeof AppReviewRoute
  '/romaji': typeof AppRomajiRoute
  '/settings': typeof AppSettingsRoute
  '/songs': typeof AppSongsRouteWithChildren
  '/stats': typeof AppStatsRoute
  '/vocabulary': typeof AppVocabularyRouteWithChildren
  '/dictionary/$id': typeof AppDictionaryIdRoute
  '/grammar/$id': typeof AppGrammarIdRoute
  '/hiragana/$id': typeof AppHiraganaIdRoute
  '/kanji/$id': typeof AppKanjiIdRoute
  '/katakana/$id': typeof AppKatakanaIdRoute
  '/path/$id': typeof AppPathIdRoute
  '/radicals/$id': typeof AppRadicalsIdRoute
  '/songs/$id': typeof AppSongsIdRoute
  '/tools/import-dictionary': typeof AppToolsImportDictionaryRoute
  '/vocabulary/$id': typeof AppVocabularyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dictionary/': typeof AppDictionaryIndexRoute
  '/grammar/': typeof AppGrammarIndexRoute
  '/hiragana/': typeof AppHiraganaIndexRoute
  '/kanji/': typeof AppKanjiIndexRoute
  '/katakana/': typeof AppKatakanaIndexRoute
  '/path/': typeof AppPathIndexRoute
  '/radicals/': typeof AppRadicalsIndexRoute
  '/songs/': typeof AppSongsIndexRoute
  '/vocabulary/': typeof AppVocabularyIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alphabet': typeof AppAlphabetRoute
  '/daily': typeof AppDailyRoute
  '/favorites': typeof AppFavoritesRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/garden': typeof AppGardenRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/listen': typeof AppListenRoute
  '/my-words': typeof AppMyWordsRoute
  '/play': typeof AppPlayRoute
  '/quiz': typeof AppQuizRoute
  '/read': typeof AppReadRoute
  '/review': typeof AppReviewRoute
  '/romaji': typeof AppRomajiRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/': typeof AppIndexRoute
  '/dictionary/$id': typeof AppDictionaryIdRoute
  '/grammar/$id': typeof AppGrammarIdRoute
  '/hiragana/$id': typeof AppHiraganaIdRoute
  '/kanji/$id': typeof AppKanjiIdRoute
  '/katakana/$id': typeof AppKatakanaIdRoute
  '/path/$id': typeof AppPathIdRoute
  '/radicals/$id': typeof AppRadicalsIdRoute
  '/songs/$id': typeof AppSongsIdRoute
  '/tools/import-dictionary': typeof AppToolsImportDictionaryRoute
  '/vocabulary/$id': typeof AppVocabularyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dictionary': typeof AppDictionaryIndexRoute
  '/grammar': typeof AppGrammarIndexRoute
  '/hiragana': typeof AppHiraganaIndexRoute
  '/kanji': typeof AppKanjiIndexRoute
  '/katakana': typeof AppKatakanaIndexRoute
  '/path': typeof AppPathIndexRoute
  '/radicals': typeof AppRadicalsIndexRoute
  '/songs': typeof AppSongsIndexRoute
  '/vocabulary': typeof AppVocabularyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alphabet': typeof AppAlphabetRoute
  '/_app/daily': typeof AppDailyRoute
  '/_app/dictionary': typeof AppDictionaryRouteWithChildren
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/flashcards': typeof AppFlashcardsRoute
  '/_app/garden': typeof AppGardenRoute
  '/_app/grammar': typeof AppGrammarRouteWithChildren
  '/_app/hiragana': typeof AppHiraganaRouteWithChildren
  '/_app/kanji': typeof AppKanjiRouteWithChildren
  '/_app/katakana': typeof AppKatakanaRouteWithChildren
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/listen': typeof AppListenRoute
  '/_app/my-words': typeof AppMyWordsRoute
  '/_app/path': typeof AppPathRouteWithChildren
  '/_app/play': typeof AppPlayRoute
  '/_app/quiz': typeof AppQuizRoute
  '/_app/radicals': typeof AppRadicalsRouteWithChildren
  '/_app/read': typeof AppReadRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/romaji': typeof AppRomajiRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/songs': typeof AppSongsRouteWithChildren
  '/_app/stats': typeof AppStatsRoute
  '/_app/vocabulary': typeof AppVocabularyRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/dictionary/$id': typeof AppDictionaryIdRoute
  '/_app/grammar/$id': typeof AppGrammarIdRoute
  '/_app/hiragana/$id': typeof AppHiraganaIdRoute
  '/_app/kanji/$id': typeof AppKanjiIdRoute
  '/_app/katakana/$id': typeof AppKatakanaIdRoute
  '/_app/path/$id': typeof AppPathIdRoute
  '/_app/radicals/$id': typeof AppRadicalsIdRoute
  '/_app/songs/$id': typeof AppSongsIdRoute
  '/_app/tools/import-dictionary': typeof AppToolsImportDictionaryRoute
  '/_app/vocabulary/$id': typeof AppVocabularyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/dictionary/': typeof AppDictionaryIndexRoute
  '/_app/grammar/': typeof AppGrammarIndexRoute
  '/_app/hiragana/': typeof AppHiraganaIndexRoute
  '/_app/kanji/': typeof AppKanjiIndexRoute
  '/_app/katakana/': typeof AppKatakanaIndexRoute
  '/_app/path/': typeof AppPathIndexRoute
  '/_app/radicals/': typeof AppRadicalsIndexRoute
  '/_app/songs/': typeof AppSongsIndexRoute
  '/_app/vocabulary/': typeof AppVocabularyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alphabet'
    | '/daily'
    | '/dictionary'
    | '/favorites'
    | '/flashcards'
    | '/garden'
    | '/grammar'
    | '/hiragana'
    | '/kanji'
    | '/katakana'
    | '/leaderboard'
    | '/listen'
    | '/my-words'
    | '/path'
    | '/play'
    | '/quiz'
    | '/radicals'
    | '/read'
    | '/review'
    | '/romaji'
    | '/settings'
    | '/songs'
    | '/stats'
    | '/vocabulary'
    | '/dictionary/$id'
    | '/grammar/$id'
    | '/hiragana/$id'
    | '/kanji/$id'
    | '/katakana/$id'
    | '/path/$id'
    | '/radicals/$id'
    | '/songs/$id'
    | '/tools/import-dictionary'
    | '/vocabulary/$id'
    | '/api/auth/$'
    | '/dictionary/'
    | '/grammar/'
    | '/hiragana/'
    | '/kanji/'
    | '/katakana/'
    | '/path/'
    | '/radicals/'
    | '/songs/'
    | '/vocabulary/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alphabet'
    | '/daily'
    | '/favorites'
    | '/flashcards'
    | '/garden'
    | '/leaderboard'
    | '/listen'
    | '/my-words'
    | '/play'
    | '/quiz'
    | '/read'
    | '/review'
    | '/romaji'
    | '/settings'
    | '/stats'
    | '/'
    | '/dictionary/$id'
    | '/grammar/$id'
    | '/hiragana/$id'
    | '/kanji/$id'
    | '/katakana/$id'
    | '/path/$id'
    | '/radicals/$id'
    | '/songs/$id'
    | '/tools/import-dictionary'
    | '/vocabulary/$id'
    | '/api/auth/$'
    | '/dictionary'
    | '/grammar'
    | '/hiragana'
    | '/kanji'
    | '/katakana'
    | '/path'
    | '/radicals'
    | '/songs'
    | '/vocabulary'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/alphabet'
    | '/_app/daily'
    | '/_app/dictionary'
    | '/_app/favorites'
    | '/_app/flashcards'
    | '/_app/garden'
    | '/_app/grammar'
    | '/_app/hiragana'
    | '/_app/kanji'
    | '/_app/katakana'
    | '/_app/leaderboard'
    | '/_app/listen'
    | '/_app/my-words'
    | '/_app/path'
    | '/_app/play'
    | '/_app/quiz'
    | '/_app/radicals'
    | '/_app/read'
    | '/_app/review'
    | '/_app/romaji'
    | '/_app/settings'
    | '/_app/songs'
    | '/_app/stats'
    | '/_app/vocabulary'
    | '/_app/'
    | '/_app/dictionary/$id'
    | '/_app/grammar/$id'
    | '/_app/hiragana/$id'
    | '/_app/kanji/$id'
    | '/_app/katakana/$id'
    | '/_app/path/$id'
    | '/_app/radicals/$id'
    | '/_app/songs/$id'
    | '/_app/tools/import-dictionary'
    | '/_app/vocabulary/$id'
    | '/api/auth/$'
    | '/_app/dictionary/'
    | '/_app/grammar/'
    | '/_app/hiragana/'
    | '/_app/kanji/'
    | '/_app/katakana/'
    | '/_app/path/'
    | '/_app/radicals/'
    | '/_app/songs/'
    | '/_app/vocabulary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alphabet': {
      id: '/_app/alphabet'
      path: '/alphabet'
      fullPath: '/alphabet'
      preLoaderRoute: typeof AppAlphabetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily': {
      id: '/_app/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AppDailyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dictionary': {
      id: '/_app/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof AppDictionaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flashcards': {
      id: '/_app/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/garden': {
      id: '/_app/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof AppGardenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grammar': {
      id: '/_app/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof AppGrammarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hiragana': {
      id: '/_app/hiragana'
      path: '/hiragana'
      fullPath: '/hiragana'
      preLoaderRoute: typeof AppHiraganaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanji': {
      id: '/_app/kanji'
      path: '/kanji'
      fullPath: '/kanji'
      preLoaderRoute: typeof AppKanjiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/katakana': {
      id: '/_app/katakana'
      path: '/katakana'
      fullPath: '/katakana'
      preLoaderRoute: typeof AppKatakanaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listen': {
      id: '/_app/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof AppListenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-words': {
      id: '/_app/my-words'
      path: '/my-words'
      fullPath: '/my-words'
      preLoaderRoute: typeof AppMyWordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/path': {
      id: '/_app/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof AppPathRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play': {
      id: '/_app/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz': {
      id: '/_app/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/radicals': {
      id: '/_app/radicals'
      path: '/radicals'
      fullPath: '/radicals'
      preLoaderRoute: typeof AppRadicalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/read': {
      id: '/_app/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof AppReadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/romaji': {
      id: '/_app/romaji'
      path: '/romaji'
      fullPath: '/romaji'
      preLoaderRoute: typeof AppRomajiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/songs': {
      id: '/_app/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof AppSongsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vocabulary': {
      id: '/_app/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AppVocabularyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dictionary/': {
      id: '/_app/dictionary/'
      path: '/'
      fullPath: '/dictionary/'
      preLoaderRoute: typeof AppDictionaryIndexRouteImport
      parentRoute: typeof AppDictionaryRoute
    }
    '/_app/dictionary/$id': {
      id: '/_app/dictionary/$id'
      path: '/$id'
      fullPath: '/dictionary/$id'
      preLoaderRoute: typeof AppDictionaryIdRouteImport
      parentRoute: typeof AppDictionaryRoute
    }
    '/_app/grammar/': {
      id: '/_app/grammar/'
      path: '/'
      fullPath: '/grammar/'
      preLoaderRoute: typeof AppGrammarIndexRouteImport
      parentRoute: typeof AppGrammarRoute
    }
    '/_app/grammar/$id': {
      id: '/_app/grammar/$id'
      path: '/$id'
      fullPath: '/grammar/$id'
      preLoaderRoute: typeof AppGrammarIdRouteImport
      parentRoute: typeof AppGrammarRoute
    }
    '/_app/hiragana/': {
      id: '/_app/hiragana/'
      path: '/'
      fullPath: '/hiragana/'
      preLoaderRoute: typeof AppHiraganaIndexRouteImport
      parentRoute: typeof AppHiraganaRoute
    }
    '/_app/hiragana/$id': {
      id: '/_app/hiragana/$id'
      path: '/$id'
      fullPath: '/hiragana/$id'
      preLoaderRoute: typeof AppHiraganaIdRouteImport
      parentRoute: typeof AppHiraganaRoute
    }
    '/_app/kanji/': {
      id: '/_app/kanji/'
      path: '/'
      fullPath: '/kanji/'
      preLoaderRoute: typeof AppKanjiIndexRouteImport
      parentRoute: typeof AppKanjiRoute
    }
    '/_app/kanji/$id': {
      id: '/_app/kanji/$id'
      path: '/$id'
      fullPath: '/kanji/$id'
      preLoaderRoute: typeof AppKanjiIdRouteImport
      parentRoute: typeof AppKanjiRoute
    }
    '/_app/katakana/': {
      id: '/_app/katakana/'
      path: '/'
      fullPath: '/katakana/'
      preLoaderRoute: typeof AppKatakanaIndexRouteImport
      parentRoute: typeof AppKatakanaRoute
    }
    '/_app/katakana/$id': {
      id: '/_app/katakana/$id'
      path: '/$id'
      fullPath: '/katakana/$id'
      preLoaderRoute: typeof AppKatakanaIdRouteImport
      parentRoute: typeof AppKatakanaRoute
    }
    '/_app/path/': {
      id: '/_app/path/'
      path: '/'
      fullPath: '/path/'
      preLoaderRoute: typeof AppPathIndexRouteImport
      parentRoute: typeof AppPathRoute
    }
    '/_app/path/$id': {
      id: '/_app/path/$id'
      path: '/$id'
      fullPath: '/path/$id'
      preLoaderRoute: typeof AppPathIdRouteImport
      parentRoute: typeof AppPathRoute
    }
    '/_app/radicals/': {
      id: '/_app/radicals/'
      path: '/'
      fullPath: '/radicals/'
      preLoaderRoute: typeof AppRadicalsIndexRouteImport
      parentRoute: typeof AppRadicalsRoute
    }
    '/_app/radicals/$id': {
      id: '/_app/radicals/$id'
      path: '/$id'
      fullPath: '/radicals/$id'
      preLoaderRoute: typeof AppRadicalsIdRouteImport
      parentRoute: typeof AppRadicalsRoute
    }
    '/_app/songs/': {
      id: '/_app/songs/'
      path: '/'
      fullPath: '/songs/'
      preLoaderRoute: typeof AppSongsIndexRouteImport
      parentRoute: typeof AppSongsRoute
    }
    '/_app/songs/$id': {
      id: '/_app/songs/$id'
      path: '/$id'
      fullPath: '/songs/$id'
      preLoaderRoute: typeof AppSongsIdRouteImport
      parentRoute: typeof AppSongsRoute
    }
    '/_app/tools/import-dictionary': {
      id: '/_app/tools/import-dictionary'
      path: '/tools/import-dictionary'
      fullPath: '/tools/import-dictionary'
      preLoaderRoute: typeof AppToolsImportDictionaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vocabulary/': {
      id: '/_app/vocabulary/'
      path: '/'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof AppVocabularyIndexRouteImport
      parentRoute: typeof AppVocabularyRoute
    }
    '/_app/vocabulary/$id': {
      id: '/_app/vocabulary/$id'
      path: '/$id'
      fullPath: '/vocabulary/$id'
      preLoaderRoute: typeof AppVocabularyIdRouteImport
      parentRoute: typeof AppVocabularyRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDictionaryRouteChildren {
  AppDictionaryIdRoute: typeof AppDictionaryIdRoute
  AppDictionaryIndexRoute: typeof AppDictionaryIndexRoute
}

const AppDictionaryRouteChildren: AppDictionaryRouteChildren = {
  AppDictionaryIdRoute: AppDictionaryIdRoute,
  AppDictionaryIndexRoute: AppDictionaryIndexRoute,
}

const AppDictionaryRouteWithChildren = AppDictionaryRoute._addFileChildren(
  AppDictionaryRouteChildren,
)

interface AppGrammarRouteChildren {
  AppGrammarIdRoute: typeof AppGrammarIdRoute
  AppGrammarIndexRoute: typeof AppGrammarIndexRoute
}

const AppGrammarRouteChildren: AppGrammarRouteChildren = {
  AppGrammarIdRoute: AppGrammarIdRoute,
  AppGrammarIndexRoute: AppGrammarIndexRoute,
}

const AppGrammarRouteWithChildren = AppGrammarRoute._addFileChildren(
  AppGrammarRouteChildren,
)

interface AppHiraganaRouteChildren {
  AppHiraganaIdRoute: typeof AppHiraganaIdRoute
  AppHiraganaIndexRoute: typeof AppHiraganaIndexRoute
}

const AppHiraganaRouteChildren: AppHiraganaRouteChildren = {
  AppHiraganaIdRoute: AppHiraganaIdRoute,
  AppHiraganaIndexRoute: AppHiraganaIndexRoute,
}

const AppHiraganaRouteWithChildren = AppHiraganaRoute._addFileChildren(
  AppHiraganaRouteChildren,
)

interface AppKanjiRouteChildren {
  AppKanjiIdRoute: typeof AppKanjiIdRoute
  AppKanjiIndexRoute: typeof AppKanjiIndexRoute
}

const AppKanjiRouteChildren: AppKanjiRouteChildren = {
  AppKanjiIdRoute: AppKanjiIdRoute,
  AppKanjiIndexRoute: AppKanjiIndexRoute,
}

const AppKanjiRouteWithChildren = AppKanjiRoute._addFileChildren(
  AppKanjiRouteChildren,
)

interface AppKatakanaRouteChildren {
  AppKatakanaIdRoute: typeof AppKatakanaIdRoute
  AppKatakanaIndexRoute: typeof AppKatakanaIndexRoute
}

const AppKatakanaRouteChildren: AppKatakanaRouteChildren = {
  AppKatakanaIdRoute: AppKatakanaIdRoute,
  AppKatakanaIndexRoute: AppKatakanaIndexRoute,
}

const AppKatakanaRouteWithChildren = AppKatakanaRoute._addFileChildren(
  AppKatakanaRouteChildren,
)

interface AppPathRouteChildren {
  AppPathIdRoute: typeof AppPathIdRoute
  AppPathIndexRoute: typeof AppPathIndexRoute
}

const AppPathRouteChildren: AppPathRouteChildren = {
  AppPathIdRoute: AppPathIdRoute,
  AppPathIndexRoute: AppPathIndexRoute,
}

const AppPathRouteWithChildren =
  AppPathRoute._addFileChildren(AppPathRouteChildren)

interface AppRadicalsRouteChildren {
  AppRadicalsIdRoute: typeof AppRadicalsIdRoute
  AppRadicalsIndexRoute: typeof AppRadicalsIndexRoute
}

const AppRadicalsRouteChildren: AppRadicalsRouteChildren = {
  AppRadicalsIdRoute: AppRadicalsIdRoute,
  AppRadicalsIndexRoute: AppRadicalsIndexRoute,
}

const AppRadicalsRouteWithChildren = AppRadicalsRoute._addFileChildren(
  AppRadicalsRouteChildren,
)

interface AppSongsRouteChildren {
  AppSongsIdRoute: typeof AppSongsIdRoute
  AppSongsIndexRoute: typeof AppSongsIndexRoute
}

const AppSongsRouteChildren: AppSongsRouteChildren = {
  AppSongsIdRoute: AppSongsIdRoute,
  AppSongsIndexRoute: AppSongsIndexRoute,
}

const AppSongsRouteWithChildren = AppSongsRoute._addFileChildren(
  AppSongsRouteChildren,
)

interface AppVocabularyRouteChildren {
  AppVocabularyIdRoute: typeof AppVocabularyIdRoute
  AppVocabularyIndexRoute: typeof AppVocabularyIndexRoute
}

const AppVocabularyRouteChildren: AppVocabularyRouteChildren = {
  AppVocabularyIdRoute: AppVocabularyIdRoute,
  AppVocabularyIndexRoute: AppVocabularyIndexRoute,
}

const AppVocabularyRouteWithChildren = AppVocabularyRoute._addFileChildren(
  AppVocabularyRouteChildren,
)

interface AppRouteChildren {
  AppAlphabetRoute: typeof AppAlphabetRoute
  AppDailyRoute: typeof AppDailyRoute
  AppDictionaryRoute: typeof AppDictionaryRouteWithChildren
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppGardenRoute: typeof AppGardenRoute
  AppGrammarRoute: typeof AppGrammarRouteWithChildren
  AppHiraganaRoute: typeof AppHiraganaRouteWithChildren
  AppKanjiRoute: typeof AppKanjiRouteWithChildren
  AppKatakanaRoute: typeof AppKatakanaRouteWithChildren
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppListenRoute: typeof AppListenRoute
  AppMyWordsRoute: typeof AppMyWordsRoute
  AppPathRoute: typeof AppPathRouteWithChildren
  AppPlayRoute: typeof AppPlayRoute
  AppQuizRoute: typeof AppQuizRoute
  AppRadicalsRoute: typeof AppRadicalsRouteWithChildren
  AppReadRoute: typeof AppReadRoute
  AppReviewRoute: typeof AppReviewRoute
  AppRomajiRoute: typeof AppRomajiRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSongsRoute: typeof AppSongsRouteWithChildren
  AppStatsRoute: typeof AppStatsRoute
  AppVocabularyRoute: typeof AppVocabularyRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppToolsImportDictionaryRoute: typeof AppToolsImportDictionaryRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlphabetRoute: AppAlphabetRoute,
  AppDailyRoute: AppDailyRoute,
  AppDictionaryRoute: AppDictionaryRouteWithChildren,
  AppFavoritesRoute: AppFavoritesRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppGardenRoute: AppGardenRoute,
  AppGrammarRoute: AppGrammarRouteWithChildren,
  AppHiraganaRoute: AppHiraganaRouteWithChildren,
  AppKanjiRoute: AppKanjiRouteWithChildren,
  AppKatakanaRoute: AppKatakanaRouteWithChildren,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppListenRoute: AppListenRoute,
  AppMyWordsRoute: AppMyWordsRoute,
  AppPathRoute: AppPathRouteWithChildren,
  AppPlayRoute: AppPlayRoute,
  AppQuizRoute: AppQuizRoute,
  AppRadicalsRoute: AppRadicalsRouteWithChildren,
  AppReadRoute: AppReadRoute,
  AppReviewRoute: AppReviewRoute,
  AppRomajiRoute: AppRomajiRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSongsRoute: AppSongsRouteWithChildren,
  AppStatsRoute: AppStatsRoute,
  AppVocabularyRoute: AppVocabularyRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppToolsImportDictionaryRoute: AppToolsImportDictionaryRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
